In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.3

In [5]:
df=pd.read_csv("retail_store_inventory.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [7]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [8]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [9]:
df.tail()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [10]:
df.describe(include="all")

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
count,73100,73100,73100,73100,73100,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100,73100.000000,73100.000000,73100
unique,731,5,20,5,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,4
top,2022-01-01,S001,P0001,Furniture,East,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,NaN,NaN,Spring
freq,100,14620,3655,14699,18349,NaN,NaN,NaN,NaN,NaN,NaN,18290,NaN,NaN,18317
mean,NaN,NaN,NaN,NaN,NaN,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,NaN,0.497305,55.146077,NaN
std,NaN,NaN,NaN,NaN,NaN,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,NaN,0.499996,26.191408,NaN
min,NaN,NaN,NaN,NaN,NaN,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,NaN,0.000000,5.030000,NaN
25%,NaN,NaN,NaN,NaN,NaN,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,NaN,0.000000,32.680000,NaN
50%,NaN,NaN,NaN,NaN,NaN,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,NaN,0.000000,55.010000,NaN
75%,NaN,NaN,NaN,NaN,NaN,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,NaN,1.000000,77.820000,NaN
max,NaN,NaN,NaN,NaN,NaN,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,NaN,1.000000,104.940000,NaN

In [11]:
df.isnull()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73096,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73097,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73098,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73099,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [15]:
df=df.drop_duplicates()

In [16]:
df=df.fillna(0)

In [18]:
df['Revenue'] = (
    df['Units Sold'] *
    df['Price']
)

In [19]:
df['Revenue']

0         4254.50
1         9451.50
2         1819.35
3         1995.92
4         1030.96
           ...
73095      589.84
73096     4211.07
73097      399.96
73098    14028.96
73099      470.34
Name: Revenue, Length: 73100, dtype: float64

In [22]:
print(df.columns.tolist())

['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Revenue']

In [23]:
df['Profit'] = (
df['Revenue'] * 0.30
)

In [25]:
df['Profit']

0        1276.350
1        2835.450
2         545.805
3         598.776
4         309.288
           ...
73095     176.952
73096    1263.321
73097     119.988
73098    4208.688
73099     141.102
Name: Profit, Length: 73100, dtype: float64

In [27]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['Date', 'Store_ID', 'Product_ID', 'Category', 'Region',
       'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast',
       'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion',
       'Competitor_Pricing', 'Seasonality', 'Revenue', 'Profit'],
      dtype='object')

In [28]:
df['Revenue'] = (
    df['Units_Sold'] *
    df['Price']
)

In [29]:
df['Revenue']

0         4254.50
1         9451.50
2         1819.35
3         1995.92
4         1030.96
           ...
73095      589.84
73096     4211.07
73097      399.96
73098    14028.96
73099      470.34
Name: Revenue, Length: 73100, dtype: float64

In [30]:
df[['Units_Sold','Price','Revenue']].head()

   Units_Sold  Price  Revenue
0         127  33.50  4254.50
1         150  63.01  9451.50
2          65  27.99  1819.35
3          61  32.72  1995.92
4          14  73.64  1030.96

In [31]:
print(df.columns.tolist())

['Date', 'Store_ID', 'Product_ID', 'Category', 'Region', 'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast', 'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion', 'Competitor_Pricing', 'Seasonality', 'Revenue', 'Profit']

In [32]:
df['Average_Sales']=(
df['Revenue']/
df['Units_Sold']
)

In [35]:
df['Average_Sales']

0        33.50
1        63.01
2        27.99
3        32.72
4        73.64
         ...
73095    73.73
73096    82.57
73097    11.11
73098    53.14
73099    78.39
Name: Average_Sales, Length: 73100, dtype: float64

In [36]:
df.head()

,Date,Store_ID,Product_ID,Category,Region,Inventory_Level,Units_Sold,Units_Ordered,Demand_Forecast,Price,Discount,Weather_Condition,Holiday/Promotion,Competitor_Pricing,Seasonality,Revenue,Profit,Average_Sales
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,4254.50,1276.350,33.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,9451.50,2835.450,63.01
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,1819.35,545.805,27.99
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,1995.92,598.776,32.72
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,1030.96,309.288,73.64

In [37]:
print(df)

             Date Store_ID Product_ID     Category Region  Inventory_Level  \
0      2022-01-01     S001      P0001    Groceries  North              231
1      2022-01-01     S001      P0002         Toys  South              204
2      2022-01-01     S001      P0003         Toys   West              102
3      2022-01-01     S001      P0004         Toys  North              469
4      2022-01-01     S001      P0005  Electronics   East              166
...           ...      ...        ...          ...    ...              ...
73095  2024-01-01     S005      P0016    Furniture   East               96
73096  2024-01-01     S005      P0017         Toys  North              313
73097  2024-01-01     S005      P0018     Clothing   West              278
73098  2024-01-01     S005      P0019         Toys   East              374
73099  2024-01-01     S005      P0020    Groceries   East              117

       Units_Sold  Units_Ordered  Demand_Forecast  Price  Discount  \
0             127             55           135.47  33.50        20
1             150             66           144.04  63.01        20
2              65             51            74.02  27.99        10
3              61            164            62.18  32.72        10
4              14            135             9.26  73.64         0
...           ...            ...              ...    ...       ...
73095           8            127            18.46  73.73        20
73096          51            101            48.43  82.57        10
73097          36            151            39.65  11.11        10
73098         264             21           270.52  53.14        20
73099           6            165             2.33  78.39        20

      Weather_Condition  Holiday/Promotion  Competitor_Pricing Seasonality  \
0                 Rainy                  0               29.69      Autumn
1                 Sunny                  0               66.16      Autumn
2                 Sunny                  1               31.32      Summer
3                Cloudy                  1               34.74      Autumn
4                 Sunny                  0               68.95      Summer
...                 ...                ...                 ...         ...
73095             Snowy                  0               72.45      Winter
73096            Cloudy                  0               83.78      Autumn
73097             Rainy                  0               10.91      Winter
73098             Rainy                  0               55.80      Spring
73099             Rainy                  1               79.52      Spring

        Revenue    Profit  Average_Sales
0       4254.50  1276.350          33.50
1       9451.50  2835.450          63.01
2       1819.35   545.805          27.99
3       1995.92   598.776          32.72
4       1030.96   309.288          73.64
...         ...       ...            ...
73095    589.84   176.952          73.73
73096   4211.07  1263.321          82.57
73097    399.96   119.988          11.11
73098  14028.96  4208.688          53.14
73099    470.34   141.102          78.39

[73100 rows x 18 columns]

In [41]:
top=df.groupby('Product_ID')['Revenue'].sum()
top.sort_values(ascending=False).head(10)

Product_ID
P0020    28306192.40
P0011    28155025.56
P0016    28153328.38
P0014    28110375.77
P0005    27916663.02
P0013    27914863.65
P0015    27742249.64
P0009    27675549.22
P0007    27632505.00
P0001    27477692.24
Name: Revenue, dtype: float64

In [50]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['Date', 'Store_ID', 'Product_ID', 'Category', 'Region',
       'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast',
       'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion',
       'Competitor_Pricing', 'Seasonality', 'Revenue', 'Profit',
       'Average_Sales'],
      dtype='object')

In [51]:
# Average inventory by region
avg_inventory = (
    df.groupby("Region")["Inventory_Level"]
    .mean()
    .reset_index()
)

print(avg_inventory)

  Region  Inventory_Level
0   East       275.292659
1  North       274.796632
2  South       275.313221
3   West       272.468122

In [53]:
df['Date'] = pd.to_datetime(
df['Date'],
errors='coerce'
)

In [54]:
print(df['Date'].dtype)

datetime64[ns]

In [55]:
monthly = df.groupby(
df['Date'].dt.month
)['Revenue'].sum()

print(monthly)

Date
1     47045983.36
2     42611326.56
3     47358641.61
4     45035185.63
5     45816017.88
6     45615579.50
7     47286030.14
8     46213010.73
9     44956005.61
10    46670250.23
11    46177435.18
12    45443418.48
Name: Revenue, dtype: float64

In [56]:
df['Month'] = (
df['Date']
.dt.month_name()
)

print(
df[['Date','Month']]
.head()
)

        Date    Month
0 2022-01-01  January
1 2022-01-01  January
2 2022-01-01  January
3 2022-01-01  January
4 2022-01-01  January

In [57]:
print(df.columns.tolist())

['Date', 'Store_ID', 'Product_ID', 'Category', 'Region', 'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast', 'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion', 'Competitor_Pricing', 'Seasonality', 'Revenue', 'Profit', 'Average_Sales', 'Month']

In [58]:
pip install pandas numpy matplotlib sqlalchemy psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Collecting psycopg2
  Downloading psycopg2-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 6.1 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.8 MB 6.3 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 5.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.2 MB/s  0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [62]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Load CSV
df = pd.read_csv("retail_store_inventory.csv")

# Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

# PostgreSQL connection
username = "postgres"
password = quote_plus("Nisha@123")   # encode special characters
host = "localhost"
port = "5432"
database = "Retail Store"

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Test connection
try:
    with engine.connect() as conn:
        print("Connected Successfully!")

    # Upload dataset
    df.to_sql(
        name="retail_inventory",
        con=engine,
        if_exists="replace",
        index=False
    )

    print("Data loaded into PostgreSQL successfully!")

except Exception as e:
    print("Error:", e)

Connected Successfully!
Data loaded into PostgreSQL successfully!